[general]
#Main url
url = "https://greenhouse.example.com"

#Port to listen for Web
port = 8000
address = "0.0.0.0"

#path to the data dir (containing templates and static folders)
data = "/usr/local/share/greenhouse"

[database]
dsn = "host=localhost user=gorm password=gorm dbname=greenhouse port=9920 sslmode=disable TimeZone=Europe/Paris"

[log]
# default is used for all unspecified module level
# can be any of: trace, debug, info, warning, error, fatal, panic
default = "info"
app = "info"
database = "trace"
gorm = "trace"
